config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:todo Metrics/BlockLength
  get 'auth_tokens/edit'
  post 'auth_tokens/update'
  get 'pages/home'
  get '/dashboard', to: 'dashboard#show'
  get '/days', to: 'days#index'
  post '/days', to: 'days#store'
  delete '/', to: 'pages#home'
  get '/how-to', to: 'pages#howto'

  resources :goals do
    resources :goal_logs, only: [:index]
  end

  resources :repertoire_pieces, except: [:show] do
    member do
      post 'raise_level'
      post 'keep_level'
      post 'lower_level'
      post 'rollback_practice'
    end
  end

  resources :absence_periods
  resources :practice_plans do
    member do
      post 'duplicate'
    end
  end

  get '/u/:username', to: 'user_profiles#show', as: 'user_profiles_show'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!

  def show # rubocop:todo Metrics/AbcSize, Metrics/MethodLength
    @today = current_user.days.today.first.time_in_seconds
    @yesterday = current_user.days.yesterday.first.time_in_seconds
    last_seven_days = current_user.days.last_7_days
    @sum7 = last_seven_days.to_a.reduce(0) { |sum, day| sum + day[:time_in_seconds] }

    last30 = current_user.days.last_30_days.sort_by(&:date).each_with_object({}) do |day, accum|
      accum[day.date] = day.time_in_seconds / 60
    end
    @last_30_days = ((Date.today - 29.days)..Date.today).each_with_object({}) do |date, hash|
      hash[date.to_s] = last30.fetch(date, 0)
    end

    date = Date.today
    @sum_month = current_user.days.where(date: (date.beginning_of_month..date.end_of_month)).sum(:time_in_seconds)
    @sum_year = current_user.days.where(date: (date.beginning_of_year..date.end_of_year)).sum(:time_in_seconds)
    @sum_all = current_user.days.sum(:time_in_seconds)

    @repertoire_piece = RepertoirePiece.get_due_today(current_user)
    @daily_goal = current_user.daily_goal
    @weekly_goal = current_user.weekly_goal

    h = {}
    ((date - 1.year).beginning_of_week..date).each { |x| h[x.strftime] = 0 }

    days = current_user.days.where(date: ((date - 1.year).beginning_of_week..date))
    days.each { |day| h[day.date.strftime] = day.time_in_seconds }
    @div = h.values.max / 5
    @h = h
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/views/dashboard/show.html.erb
<div class="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8">
  <div class="md:flex md:items-center md:justify-between mb-4">
    <div class="flex-1 min-w-0">
      <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">Welcome, <%= current_user.username %></h2>
    </div>
  </div>

  <% if @repertoire_piece %>
    <div class="bg-white shadow sm:rounded-lg">
      <div class="px-4 py-5 sm:p-6">
        <div>
          <div class="leading-6 text-gray-900">Repertoire Practice</div>
          <div class="text-lg">
            <span class="font-medium"><%= @repertoire_piece.name %></span> by
            <span class="font-medium"><%= @repertoire_piece.composer %></span>
          </div>
        </div>
        <% unless @repertoire_piece.revised_today? %>
          <% if @repertoire_piece.last_practice %>
            <div class="mt-2 max-w-xl text-sm text-gray-500">
              <p>Were you able to play this piece from memory to a satisfactory standard?</p>
            </div>
            <div class="md:mt-2">
              <% if @repertoire_piece.level > 1 %>
                <%= button_to "Hard, show again in #{RepertoirePiece::DAYS_INTERVALS[@repertoire_piece.level - 2]} days", lower_level_repertoire_piece_path(@repertoire_piece), method: :post, form: { class: "inline" }, class: "mt-2 inline-flex items-center justify-center px-2.5 py-1.5 sm:px-4 sm:py-2 border border-transparent font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 text-xs sm:text-sm mr-2" %>
              <% end %>
              <%= button_to "Satisfied, show again in #{RepertoirePiece::DAYS_INTERVALS[@repertoire_piece.level - 1]} days", keep_level_repertoire_piece_path(@repertoire_piece), method: :post, form: { class: "inline" }, class: "mt-2 inline-flex items-center justify-center px-2.5 py-1.5 sm:px-4 sm:py-2 border border-transparent font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 text-xs sm:text-sm mr-2" %>
              <%= button_to "Easy, show again in #{RepertoirePiece::DAYS_INTERVALS[@repertoire_piece.level]} days", raise_level_repertoire_piece_path(@repertoire_piece), method: :post, form: { class: "inline" }, class: "mt-2 inline-flex items-center justify-center px-2.5 py-1.5 sm:px-4 sm:py-2 border border-transparent font-medium rounded-md text-green-700 bg-green-100 hover:bg-green-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 text-xs sm:text-sm mr-2" %>
            </div>
          <% else %>
            <div class="mt-2 max-w-xl text-sm text-gray-500">
              <p>Hit the button below once you've finished playing the piece. We'll show it to you again in 5 days.
                Then
                you can decide if you need to play it more often, or if this interval works for you.</p>
            </div>
            <div class="md:mt-2">
              <%= button_to "All done, see you in 5 days", keep_level_repertoire_piece_path(@repertoire_piece), method: :post, form: { class: "inline" }, class: "mt-2 inline-flex items-center justify-center px-2.5 py-1.5 sm:px-4 sm:py-2 border border-transparent font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 text-xs sm:text-sm" %>
            </div>
          <% end %>
        <% else %>
          <div class="mt-2 max-w-xl text-sm text-gray-500">
            <p>All done for today! You told us to show you this piece
              <% case @repertoire_piece.last_practice.level_change
                 when -1 %>more often.
              <% when 0 %>after the same time again.
              <% when 1 %>less often.
              <% end %>
            </p>
          </div>
          <div class="mt-5">
            <%= button_to "Undo", rollback_practice_repertoire_piece_path(@repertoire_piece), method: :post, form: { class: "inline" }, class: "inline-flex items-center justify-center px-2.5 py-1.5 border border-transparent font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 text-xs" %>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="bg-white shadow sm:rounded-lg">
      <div class="px-4 py-5 sm:p-6">
        <h3 class="text-lg leading-6 text-gray-900">Repertoire Practice:
          <span class="font-medium">Nothing to do ¯\_(ツ)_/¯</span>
        </h3>
        <div class="mt-2 max-w-xl text-sm text-gray-500">
          <p>Play whatever you like or head over to the
            <a class="hover:underline font-medium" href="<%= repertoire_pieces_path %>">repertoire page</a> to
            add a new piece to your repertoire.</p>
        </div>
      </div>
    </div>

  <% end %>

  <dl class="my-5 grid grid-cols-2 gap-5 sm:grid-cols-4">
    <div class="px-4 py-5 bg-sky-500 shadow rounded-lg overflow-hidden sm:p-6 ">
      <dt class="text-sm font-medium text-sky-100 truncate">Today</dt>
      <dd class="mt-1 text-2xl lg:text-3xl font-semibold text-sky-100"><%= seconds_to_hms @today %></dd>
    </div>

    <div class="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
      <dt class="text-sm font-medium text-gray-500 truncate">Yesterday</dt>
      <dd class="mt-1 text-2xl lg:text-3xl font-semibold text-gray-900"><%= seconds_to_hms @yesterday %></dd>
    </div>

    <div class="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
      <dt class="text-sm font-medium text-gray-500 truncate">Last 7 Days</dt>
      <dd class="mt-1 text-2xl lg:text-3xl font-semibold text-gray-900"><%= seconds_to_hms @sum7 %></dd>
    </div>

    <div class="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
      <dt class="text-sm font-medium text-gray-500 truncate">Daily Average</dt>
      <dd class="mt-1 text-2xl lg:text-3xl font-semibold text-gray-900"><%= seconds_to_hms @sum7 / 7 %></dd>
    </div>
  </dl>
  <% if @daily_goal && @daily_goal.active %>
    <%= render "goals/progress", name: "Daily Goal", goal: @daily_goal %>
  <% end %>
  <% if @weekly_goal && @weekly_goal.active %>
    <%= render "goals/progress", name: "Weekly Goal", goal: @weekly_goal %>
  <% end %>


  <dl class="my-5 grid grid-cols-2 gap-5 sm:grid-cols-4">
    <div class="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
      <dt class="text-sm font-medium text-gray-500 truncate">This Month</dt>
      <dd class="mt-1 text-2xl lg:text-3xl font-semibold text-gray-900"><%= seconds_to_hms @sum_month %></dd>
    </div>

    <div class="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
      <dt class="text-sm font-medium text-gray-500 truncate">This Year</dt>
      <dd class="mt-1 text-2xl lg:text-3xl font-semibold text-gray-900"><%= seconds_to_hms @sum_year %></dd>
    </div>

    <div class="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
      <dt class="text-sm font-medium text-gray-500 truncate">All Time</dt>
      <dd class="mt-1 text-2xl lg:text-3xl font-semibold text-gray-900"><%= seconds_to_hms @sum_all %></dd>
    </div>
  </dl>
  <div>
    <%= render "days/grid", days: @days, h:@h, div: @div %>
  </div>
</div>