config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:todo Metrics/BlockLength
  get 'auth_tokens/edit'
  post 'auth_tokens/update'
  get 'pages/home'
  get '/dashboard', to: 'dashboard#show'
  get '/days', to: 'days#index'
  post '/days', to: 'days#store'
  delete '/', to: 'pages#home'
  get '/how-to', to: 'pages#howto'

  resources :goals do
    resources :goal_logs, only: [:index]
  end

  resources :repertoire_pieces, except: [:show] do
    member do
      post 'raise_level'
      post 'keep_level'
      post 'lower_level'
      post 'rollback_practice'
    end
  end

  resources :absence_periods
  resources :practice_plans do
    member do
      post 'duplicate'
    end
  end

  get '/u/:username', to: 'user_profiles#show', as: 'user_profiles_show'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/absence_period.rb
# frozen_string_literal: true

class AbsencePeriod < ApplicationRecord
  belongs_to :user

  scope :active, -> { where('starts_at <= ?', Date.today).where('ends_at >= ?', Date.today) }
end

app/controllers/absence_periods_controller.rb
# frozen_string_literal: true

class AbsencePeriodsController < ApplicationController
  before_action :set_absence_period, only: %i[show edit update destroy]
  before_action :authenticate_user!
  require_permission :absence_period, only: %i[show edit update destroy]

  # GET /absence_periods or /absence_periods.json
  def index
    @absence_periods = AbsencePeriod.all
  end

  # GET /absence_periods/1 or /absence_periods/1.json
  def show; end

  # GET /absence_periods/new
  def new
    @absence_period = AbsencePeriod.new
  end

  # GET /absence_periods/1/edit
  def edit; end

  # POST /absence_periods or /absence_periods.json
  def create
    @absence_period = current_user.absence_periods.new(absence_period_params)

    respond_to do |format|
      if @absence_period.save
        format.html { redirect_to absence_periods_url, notice: 'Absence period was successfully created.' }
        format.json { render :show, status: :created, location: @absence_period }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @absence_period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /absence_periods/1 or /absence_periods/1.json
  def update
    if @absence_period.update(absence_period_params)
      redirect_to absence_period_url(@absence_period), notice: 'Absence period was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /absence_periods/1 or /absence_periods/1.json
  def destroy
    @absence_period.destroy

    respond_to do |format|
      format.html { redirect_to absence_periods_url, notice: 'Absence period was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_absence_period
    @absence_period = AbsencePeriod.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def absence_period_params
    params.require(:absence_period).permit(:starts_at, :ends_at)
  end
end

app/helpers/absence_periods_helper.rb
# frozen_string_literal: true

module AbsencePeriodsHelper
end

app/views/absence_periods/_absence_period.html.erb
<div id="<%= dom_id absence_period %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Starts at:</strong>
    <%= absence_period.starts_at %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ends at:</strong>
    <%= absence_period.ends_at %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this absence period", absence_period, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this absence period', edit_absence_period_path(absence_period), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/absence_periods/_form.html.erb
<%= form_with(model: absence_period, class: "contents text-xs") do |form| %>
  <% if absence_period.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(absence_period.errors.count, "error") %> prohibited this absence_period from being saved:</h2>

      <ul>
        <% absence_period.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :starts_at %>
    <%= form.date_field :starts_at, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :ends_at %>
    <%= form.date_field :ends_at, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/absence_periods/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-2xl">Editing absence period</h1>

  <%= render "form", absence_period: @absence_period %>

  <%= button_to "Delete", @absence_period, method: :delete, form: { class: "inline", data: { turbo_confirm: 'Are you sure?' } }, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to absence periods", absence_periods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/absence_periods/index.html.erb
<div class="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold text-gray-900">Absences</h1>
      <p class="mt-2 text-sm text-gray-700">For when you're going on holiday, but don't want to lose your daily
        streak</p>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      <%= link_to 'Add absence', new_absence_period_path, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
    </div>
  </div>
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Start</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">End</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
            <% @absence_periods.each do |absence_period| %>
              <tr>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= absence_period.starts_at %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= absence_period.ends_at %></td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <%= link_to 'Edit', edit_absence_period_path(absence_period), class: "text-indigo-600 hover:text-indigo-900" %>
                </td>
              </tr>
            <% end %>

            <!-- More people... -->
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/absence_periods/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-2xl">New absence period</h1>

  <%= render "form", absence_period: @absence_period %>

  <%= link_to 'Back to absence periods', absence_periods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/absence_periods/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @absence_period %>

    <%= link_to 'Edit this absence_period', edit_absence_period_path(@absence_period), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this absence_period', absence_period_path(@absence_period), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to absence_periods', absence_periods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>