config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:todo Metrics/BlockLength
  get 'auth_tokens/edit'
  post 'auth_tokens/update'
  get 'pages/home'
  get '/dashboard', to: 'dashboard#show'
  get '/days', to: 'days#index'
  post '/days', to: 'days#store'
  delete '/', to: 'pages#home'
  get '/how-to', to: 'pages#howto'

  resources :goals do
    resources :goal_logs, only: [:index]
  end

  resources :repertoire_pieces, except: [:show] do
    member do
      post 'raise_level'
      post 'keep_level'
      post 'lower_level'
      post 'rollback_practice'
    end
  end

  resources :absence_periods
  resources :practice_plans do
    member do
      post 'duplicate'
    end
  end

  get '/u/:username', to: 'user_profiles#show', as: 'user_profiles_show'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/practice_plan.rb
# frozen_string_literal: true

class PracticePlan < ApplicationRecord
  belongs_to :user
  has_many :practice_instructions, dependent: :delete_all

  validates :name, presence: true
  validates :description, presence: true
  validates :intro, presence: true
  validates :duration, presence: true

  accepts_nested_attributes_for :practice_instructions, update_only: true

  def duplicate
    new_practice_plan = dup
    new_practice_plan.name = "Copy of #{name}"
    new_practice_plan.save!
    new_practice_plan.practice_instructions.create(
      practice_instructions.map do |instruction|
        instruction.attributes.except('id', 'created_at', 'updated_at')
      end.to_a
    )
    new_practice_plan
  end
end

app/controllers/practice_plans_controller.rb
# frozen_string_literal: true

class PracticePlansController < ApplicationController
  before_action :set_practice_plan, only: %i[show edit update destroy duplicate]
  before_action :authenticate_user!, except: %i[index show]
  before_action :hide_sidebar
  require_permission :practice_plan, only: %i[destroy], but: 'asdfa sd'

  # GET /practice_plans or /practice_plans.json
  def index
    @practice_plans = PracticePlan.all
  end

  # GET /practice_plans/1 or /practice_plans/1.json
  def show; end

  # GET /practice_plans/new
  def new
    @practice_plan = PracticePlan.new
  end

  # GET /practice_plans/1/edit
  def edit; end

  # POST /practice_plans or /practice_plans.json
  def create # rubocop:todo Metrics/AbcSize, Metrics/MethodLength
    params = practice_plan_params
    params[:user_id] = current_user.id
    @practice_plan = PracticePlan.new(params)

    respond_to do |format|
      if @practice_plan.save
        format.html do
          redirect_to edit_practice_plan_path(@practice_plan), notice: 'Practice plan was successfully created.'
        end
        format.json { render :show, status: :created, location: @practice_plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @practice_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practice_plans/1 or /practice_plans/1.json
  def update # rubocop:todo Metrics/AbcSize, Metrics/MethodLength
    respond_to do |format|
      updated = false
      ActiveRecord::Base.transaction do
        @practice_plan.practice_instructions.destroy_all
        updated = @practice_plan.update(practice_plan_params)
        raise ActiveRecord::Rollback unless updated
      end
      if updated
        format.html { redirect_to practice_plan_url(@practice_plan), notice: 'Practice plan was successfully updated.' }
        format.json do
          flash.notice = 'Practice plan was successfully updated.'
          render :show, status: :ok, location: practice_plans_path
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @practice_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practice_plans/1 or /practice_plans/1.json
  def destroy
    @practice_plan.destroy

    respond_to do |format|
      format.html { redirect_to practice_plans_url, notice: 'Practice plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /practice_plans/duplicate
  def duplicate
    @practice_plan.duplicate
    redirect_to practice_plans_url, notice: 'Practice plan was successfully duplicated.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_practice_plan
    @practice_plan = PracticePlan.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def practice_plan_params
    params.require(:practice_plan).permit(:name, :description, :intro, :duration, :tags, :show_to_guests,
                                          # rubocop:todo Layout/LineLength
                                          practice_instructions_attributes: %i[name description end_condition position seconds repetitions])
    # rubocop:enable Layout/LineLength
  end
end

app/helpers/practice_plans_helper.rb
# frozen_string_literal: true

module PracticePlansHelper
end

app/views/practice_plans/_form.html.erb
<%= form_with(model: practice_plan, class: "contents") do |form| %>
  <% if practice_plan.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(practice_plan.errors.count, "error") %> prohibited this practice_plan from being saved:</h2>

      <ul>
        <% practice_plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :intro %>
    <%= form.text_field :intro, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :duration %>
    <%= form.text_field :duration, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/practice_plans/_practice_plan.html.erb
<li id="<%= dom_id practice_plan %>" class="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow">
  <div class="px-4 py-6">
    <div class="mb-4">
      <span class="rounded-full bg-slate-400 px-2 py-1 text-xs text-slate-50"><%= practice_plan.duration %></span>
    </div>
    <div>
      <span class="text-sm font-medium hover:underline"><%= link_to practice_plan.name, practice_plan %></span>
    </div>
    <div class="px-8 py-0.5 bg-blue-400 inline-block">
    </div>
    <div class="text-xs mt-1">
      <p><%= practice_plan.description %></p>
    </div>
    <div class="mt-4">
      <% (practice_plan.tags || "").split(", ").each do |tag| %>
        <span class="inline-block rounded-full bg-blue-400 px-2 py-1 text-xs text-blue-50 mr-1"><%= tag %></span>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="mt-3">
        <%= button_to 'Duplicate', duplicate_practice_plan_path(practice_plan), method: :post, class: "text-indigo-600 hover:text-indigo-900" %>
        <%= link_to 'Edit', edit_practice_plan_path(practice_plan), class: "text-indigo-600 hover:text-indigo-900" %>
      </div>
    <% end %>
  </div>
</li>

app/views/practice_plans/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <nav class="flex mb-5" aria-label="Breadcrumb">
    <ol role="list" class="flex items-center space-x-4">
      <li>
        <div>
          <a href="<%= dashboard_path %>" class="text-gray-400 hover:text-gray-500">
            <!-- Heroicon name: mini/home -->
            <svg class="h-5 w-5 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M9.293 2.293a1 1 0 011.414 0l7 7A1 1 0 0117 11h-1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-3a1 1 0 00-1-1H9a1 1 0 00-1 1v3a1 1 0 01-1 1H5a1 1 0 01-1-1v-6H3a1 1 0 01-.707-1.707l7-7z" clip-rule="evenodd" />
            </svg>
            <span class="sr-only">Home</span>
          </a>
        </div>
      </li>

      <li>
        <div class="flex items-center">
          <!-- Heroicon name: mini/chevron-right -->
          <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
          <a href="<%= practice_plans_path %>" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">Practice Plans</a>
        </div>
      </li>

      <li>
        <div class="flex items-center">
          <!-- Heroicon name: mini/chevron-right -->
          <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
          <a href="#" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700" aria-current="page">Edit</a>
        </div>
      </li>
    </ol>
  </nav>
  <h1 class="text-2xl">Edit Practice Plan <%= @practice_plan.name %></h1>
  <div>
    <practice-plan-edit practice-plan-data='<%= @practice_plan.to_json %>' practice-instructions-data='<%= @practice_plan.practice_instructions.to_json %>'/>
  </div>
  <% if @practice_plan.user == current_user %>
    <div>
      <%= button_to "Delete Practice Plan", @practice_plan, method: :delete, form: { class: "inline", data: { turbo_confirm: 'Are you sure?' } }, class: "inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
    </div>
  <% end %>
</div>

app/views/practice_plans/index.html.erb
<div class="relative bg-indigo-800">
  <div class="absolute inset-0">
    <img class="h-full w-full object-cover" src="https://images.unsplash.com/photo-1452724931113-5ab6340ce080?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="">
    <div class="absolute inset-0 bg-indigo-800 mix-blend-multiply" aria-hidden="true"></div>
  </div>
  <div class="relative mx-auto max-w-7xl py-16 px-4 sm:px-6 lg:px-8">
    <h1 class="text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">Fryderyk Practice Plans</h1>
  </div>
</div>
<div class="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8 pt-8">
  <% if user_signed_in? %>
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-xl font-semibold text-gray-900">Practice Plans</h1>
        <p class="mt-2 text-sm text-gray-700">Bring more structure to your practice sessions.</p>
      </div>
      <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
        <%= link_to 'New Practice Plan', new_practice_plan_path, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
      </div>
    </div>
    <div class="pt-4">
      <ul role="list" class="grid grid-cols-2 gap-4 lg:grid-cols-3">
        <% @practice_plans.each do |practice_plan| %>
          <%= render practice_plan %>
        <% end %>
      </ul>
    </div>
  <% else %>
    <div class="pt-4">
      <div class="sm:flex-auto">
        <h1 class="text-4xl font-semibold text-gray-900">Welcome, Guest!</h1>
        <p class="mt-2 text-gray-700">This one's on us. Try our "Fifteen Minimal Minutes" practice plan.</p>
      </div>
    </div>
    <div class="pt-4">
      <ul role="list" class="grid grid-cols-2 gap-4 lg:grid-cols-3">
        <% @practice_plans.select { |plan| plan.show_to_guests }.each do |practice_plan| %>
          <%= render practice_plan %>
        <% end %>
        <li class="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow">
          <div class="px-4 py-6">
            <div class="mb-4">
              <span class="rounded-full bg-slate-400 px-2 py-1 text-xs text-slate-50">It's free!</span>
            </div>
            <div>
              <span class="text-sm font-medium hover:underline">Sign up for more practice plans</span>
            </div>
            <div class="px-8 py-0.5 bg-blue-400 inline-block">
            </div>
            <div class="text-xs mt-1">
              <p class="mb-2">Login to view more practice plans.</p>
              <p>Don't have an account yet? Sign up!</p>
            </div>
          </div>
        </li>
      </ul>
    </div>
    <div class="pt-8">
      <div class="sm:flex-auto">
        <h1 class="text-2xl font-semibold text-gray-900">But wait, there's more</h1>
        <p class="mt-2 text-gray-700">All of these plans are waiting for you. Sign up to get going!</p>
      </div>
    </div>
    <div class="py-4">
      <ul role="list" class="grid grid-cols-2 gap-4 lg:grid-cols-3 grayscale">
        <% @practice_plans.select { |plan| !plan.show_to_guests }.each do |practice_plan| %>
          <%= render practice_plan %>
        <% end %>
      </ul>
    </div>
    <div class="relative py-16">
      <div class="absolute inset-x-0 top-0 hidden h-1/2 bg-gray-100 lg:block" aria-hidden="true"></div>
      <div class="mx-auto max-w-7xl bg-indigo-600 lg:bg-transparent lg:px-8">
        <div class="lg:grid lg:grid-cols-12">
          <div class="relative z-10 lg:col-span-4 lg:col-start-1 lg:row-start-1 lg:bg-transparent lg:py-16">
            <div class="absolute inset-x-0 h-1/2 bg-gray-100 lg:hidden" aria-hidden="true"></div>
            <div class="mx-auto max-w-md px-4 sm:max-w-3xl sm:px-6 lg:max-w-none lg:p-0">
              <div class="aspect-w-10 aspect-h-6 sm:aspect-w-2 sm:aspect-h-1 lg:aspect-w-1">
                <img class="rounded-3xl object-cover object-center shadow-2xl" src="https://images.unsplash.com/photo-1594122230689-7f659cff55b3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="">
              </div>
            </div>
          </div>

          <div class="relative bg-indigo-600 lg:col-span-10 lg:col-start-3 lg:row-start-1 lg:grid lg:grid-cols-10 lg:items-center lg:rounded-3xl">
            <div class="absolute inset-0 hidden overflow-hidden rounded-3xl lg:block" aria-hidden="true">
              <svg class="absolute bottom-full left-full translate-y-1/3 -translate-x-2/3 transform xl:bottom-auto xl:top-0 xl:translate-y-0" width="404" height="384" fill="none" viewBox="0 0 404 384" aria-hidden="true">
                <defs>
                  <pattern id="64e643ad-2176-4f86-b3d7-f2c5da3b6a6d" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
                    <rect x="0" y="0" width="4" height="4" class="text-indigo-500" fill="currentColor"/>
                  </pattern>
                </defs>
                <rect width="404" height="384" fill="url(#64e643ad-2176-4f86-b3d7-f2c5da3b6a6d)"/>
              </svg>
              <svg class="absolute top-full -translate-y-1/3 -translate-x-1/3 transform xl:-translate-y-1/2" width="404" height="384" fill="none" viewBox="0 0 404 384" aria-hidden="true">
                <defs>
                  <pattern id="64e643ad-2176-4f86-b3d7-f2c5da3b6a6d" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
                    <rect x="0" y="0" width="4" height="4" class="text-indigo-500" fill="currentColor"/>
                  </pattern>
                </defs>
                <rect width="404" height="384" fill="url(#64e643ad-2176-4f86-b3d7-f2c5da3b6a6d)"/>
              </svg>
            </div>
            <div class="relative mx-auto max-w-md space-y-6 py-12 px-4 sm:max-w-3xl sm:py-16 sm:px-6 lg:col-span-6 lg:col-start-4 lg:max-w-none lg:p-0">
              <h2 class="text-3xl font-bold tracking-tight text-white" id="join-heading">Join Fryderyk.xyz</h2>
              <p class="text-lg text-white">Create an account to unlock all of our free practice plans. Bring more
                structure to your practice sessions and level up your skills.</p>
              <a class="block w-full rounded-md border border-transparent bg-white py-3 px-5 text-center text-base font-medium text-indigo-700 shadow-md hover:bg-gray-100 sm:inline-block sm:w-auto" href="/users/sign_up">Sign
                Up</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/practice_plans/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <nav class="flex mb-5" aria-label="Breadcrumb">
    <ol role="list" class="flex items-center space-x-4">
      <li>
        <div>
          <a href="<%= dashboard_path %>" class="text-gray-400 hover:text-gray-500">
            <!-- Heroicon name: mini/home -->
            <svg class="h-5 w-5 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M9.293 2.293a1 1 0 011.414 0l7 7A1 1 0 0117 11h-1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-3a1 1 0 00-1-1H9a1 1 0 00-1 1v3a1 1 0 01-1 1H5a1 1 0 01-1-1v-6H3a1 1 0 01-.707-1.707l7-7z" clip-rule="evenodd" />
            </svg>
            <span class="sr-only">Home</span>
          </a>
        </div>
      </li>

      <li>
        <div class="flex items-center">
          <!-- Heroicon name: mini/chevron-right -->
          <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
          <a href="<%= practice_plans_path %>" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">Practice Plans</a>
        </div>
      </li>

      <li>
        <div class="flex items-center">
          <!-- Heroicon name: mini/chevron-right -->
          <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
          <a href="#" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700" aria-current="page">New</a>
        </div>
      </li>
    </ol>
  </nav>
  <h1 class="font-bold text-4xl">New practice plan</h1>

  <%= render "form", practice_plan: @practice_plan %>

  <%= link_to 'Back to practice plans', practice_plans_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/practice_plans/show.html.erb
<div class="container mx-auto p-4 flex-grow font-body">
  <div class="rounded-md bg-yellow-50 p-4 mb-8 hidden md:block">
    <div class="flex">
      <div class="flex-shrink-0">
        <!-- Heroicon name: mini/exclamation-triangle -->
        <svg class="h-5 w-5 text-yellow-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M8.485 3.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.17 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 3.495zM10 6a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 0110 6zm0 9a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"/>
        </svg>
      </div>
      <div class="ml-3">
        <h3 class="text-sm font-medium text-yellow-800">Optimized for a mobile experience</h3>
        <div class="mt-2 text-sm text-yellow-700">
          <p>Fryderyk.xyz is designed to be used on your smart phone. Try it on a smaller screen for a better viewing
            experience.</p>
        </div>
      </div>
    </div>
  </div>
  <nav class="flex mb-5" aria-label="Breadcrumb">
    <ol role="list" class="flex items-center space-x-4">
      <li>
        <div>
          <a href="<%= practice_plans_path %>" class="text-gray-400 hover:text-gray-500">
            <!-- Heroicon name: mini/home -->
            <svg class="h-5 w-5 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M9.293 2.293a1 1 0 011.414 0l7 7A1 1 0 0117 11h-1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-3a1 1 0 00-1-1H9a1 1 0 00-1 1v3a1 1 0 01-1 1H5a1 1 0 01-1-1v-6H3a1 1 0 01-.707-1.707l7-7z" clip-rule="evenodd"/>
            </svg>
            <span class="sr-only">Home</span>
          </a>
        </div>
      </li>

      <li>
        <div class="flex items-center">
          <!-- Heroicon name: mini/chevron-right -->
          <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd"/>
          </svg>
          <a href="<%= practice_plans_path %>" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">Practice
            Plans</a>
        </div>
      </li>

      <li>
        <div class="flex items-center">
          <!-- Heroicon name: mini/chevron-right -->
          <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd"/>
          </svg>
          <a href="#" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700" aria-current="page"><%= @practice_plan.name %></a>
        </div>
      </li>
    </ol>
  </nav>
  <div class="flex flex-row justify-center">
    <practice-plan-show practice-plan-data='<%= @practice_plan.to_json %>' practice-instructions-data='<%= @practice_plan.practice_instructions.to_json %>'/>
  </div>
</div>