config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:todo Metrics/BlockLength
  get 'auth_tokens/edit'
  post 'auth_tokens/update'
  get 'pages/home'
  get '/dashboard', to: 'dashboard#show'
  get '/days', to: 'days#index'
  post '/days', to: 'days#store'
  delete '/', to: 'pages#home'
  get '/how-to', to: 'pages#howto'

  resources :goals do
    resources :goal_logs, only: [:index]
  end

  resources :repertoire_pieces, except: [:show] do
    member do
      post 'raise_level'
      post 'keep_level'
      post 'lower_level'
      post 'rollback_practice'
    end
  end

  resources :absence_periods
  resources :practice_plans do
    member do
      post 'duplicate'
    end
  end

  get '/u/:username', to: 'user_profiles#show', as: 'user_profiles_show'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/goal.rb
# frozen_string_literal: true

class Goal < ApplicationRecord
  belongs_to :user
  has_many :goal_logs, dependent: :delete_all
  validates :value, presence: true, numericality: { only_integer: true, greater_than: 0 }

  after_save do |goal|
    goal.current_log&.delete
    goal.log_achievement
  end

  def log_achievement(date = Date.today)
    return unless reached?(date)

    goal_logs.find_or_create_by(value: value,
                                time_identifier: self.class.get_time_identifier(date))
  end

  def current_log
    goal_logs.where(time_identifier: self.class.current_time_identifier).first
  end

  def reached?(date = Date.today)
    current_value(date) >= value
  end

  def percentage
    return 100 if reached?

    100 * current_value / value
  end

  def streak_active?
    streak_length.positive?
  end

  def streak_prolonged?
    reached?
  end

  def streak_length # rubocop:todo Metrics/MethodLength
    length = 0
    length += 1 if streak_prolonged?
    log = true
    past = 1
    while log
      log = goal_logs.where(time_identifier: self.class.past_time_identifier(past)).first
      if log
        length += 1
        past += 1
      end
      if skip_period(past)
        log = true
        past += 1
      end
    end
    length
  end

  def skip_period(_past)
    false
  end
end

app/controllers/goals_controller.rb
# frozen_string_literal: true

class GoalsController < ApplicationController
  before_action :set_goal, only: %i[show edit update]
  before_action :authenticate_user!
  require_permission :goal, only: %i[show edit update]

  # GET /goals or /goals.json
  def index
    current_user.daily_goal = DailyGoal.create(value: 20) unless current_user.daily_goal
    current_user.weekly_goal = WeeklyGoal.create(value: 100) unless current_user.weekly_goal
    @daily_goal = current_user.daily_goal
    @weekly_goal = current_user.weekly_goal
  end

  # GET /goals/1 or /goals/1.json
  def show; end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit; end

  # PATCH/PUT /goals/1 or /goals/1.json
  def update
    if @goal.update({ value: goal_params[:value].to_i * 60, active: goal_params[:active] })
      redirect_to goals_url, notice: 'Goal was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_goal
    @goal = Goal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def goal_params
    params.require(:goal).permit(:value, :active)
  end
end

app/helpers/goals_helper.rb
# frozen_string_literal: true

module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_with(model: goal, class: "mt-5 sm:flex sm:items-center") do |form| %>
  <% if goal.errors.any? %>

    <div id="error_explanation" class=" bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
        <% goal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-full sm:max-w-xs flex flex-row">
    <div class="sm:max-w-xs">
      <%= form.label :value, "Minutes" %>
      <%= form.number_field :value, value: goal.value / 60, min: 1, required: true, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
    </div>

    <div class="sm:max-w-xs ml-3">
      <%= form.label :active %>
      <%= form.check_box :active, class: "block mt-2 h-5 w-5" %>
    </div>
  </div>
  <div class="inline">
    <%= form.submit "Save", class: "mt-3 w-full inline-flex items-center justify-center px-4 py-2 border border-transparent shadow-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm" %>
  </div>
<% end %>

app/views/goals/_goal.html.erb
<div id="<%= dom_id goal %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Type:</strong>
    <%= goal.type %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Value:</strong>
    <%= goal.value %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Active:</strong>
    <%= goal.active %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= goal.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this goal", goal, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this goal', edit_goal_path(goal), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/goals/_progress.html.erb
<div class="mt-4">
  <div class="mb-1 text-base font-medium flex flex-row justify-between">
    <div>
      <span><%= name %></span>
      <span class="text-sm text-gray-500 ml-1"><%= seconds_to_hms goal.current_value %>
        / <%= seconds_to_hms goal.value %></span>
      <span class="text-sm text-gray-500 ml-2"><%= goal.percentage %>%</span>
      <% if goal.reached? %>
        <svg xmlns="http://www.w3.org/2000/svg" class="inline flex-shrink-0 h-4 w-4 text-indigo-600" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/>
        </svg>
      <% end %>
    </div>
    <% if goal.streak_active? %>
      <div class="flex flex-row <% unless goal.streak_prolonged? %>text-gray-400
          <% end %>">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5
          <% if goal.streak_prolonged? %>text-indigo-600
          <% end %> align-middle" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z" clip-rule="evenodd"/>
        </svg>
        <span style="line-height: 1.4rem">
        <%= goal.streak_length %>
        </span>
      </div>
    <% end %>
  </div>
  <div class="w-full bg-gray-200 rounded-full h-2.5 mb-4">
    <div class="bg-blue-600 h-2.5 rounded-full" style="width: <%= goal.percentage %>%"></div>
  </div>
</div>

app/views/goals/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing goal</h1>

  <%= render "form", goal: @goal %>

  <%= link_to "Show this goal", @goal, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to goals", goals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/goals/index.html.erb
<div class="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold text-gray-900">Your Goals</h1>
    </div>
  </div>
  <div class="md:flex md:flex-row md:space-x-4">
    <div class="mt-8 flex flex-col md:w-1/2">
      <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 rounded md:rounded-lg">
            <div class="bg-white shadow sm:rounded-lg">
              <div class="px-4 py-5 sm:p-6">
                <h3 class="text-lg leading-6 font-medium text-gray-900">Daily Goal</h3>
                <div class="mt-2 max-w-xl text-sm text-gray-500">
                  <p>How many minutes do you want to play each day?</p>
                </div>
                <%= render "form", goal: @daily_goal %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
    <div class="mt-8 flex flex-col  md:w-1/2">
      <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 rounded md:rounded-lg">
            <div class="bg-white shadow sm:rounded-lg">
              <div class="px-4 py-5 sm:p-6">
                <h3 class="text-lg leading-6 font-medium text-gray-900">Weekly Goal</h3>
                <div class="mt-2 max-w-xl text-sm text-gray-500">
                  <p>How many minutes do you want to play each week?</p>
                </div>
                <%= render "form", goal: @weekly_goal %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="md:flex md:flex-row md:space-x-10 py-4">
    <div class="bg-white shadow sm:rounded-lg">
      <div class="px-4 py-5 sm:p-6">
        <h3 class="text-lg leading-6 font-medium text-gray-900">Going on holiday?</h3>
        <div class="mt-2 max-w-xl text-sm text-gray-500">
          <p>Set an absence period, so your daily streak won't end.</p>
        </div>
        <div class="mt-5">
          <%= link_to "Set absence", absence_periods_url, class: "inline-flex items-center justify-center px-4 py-2 border border-transparent font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:text-sm" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/goals/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New goal</h1>

  <%= render "form", goal: @goal %>

  <%= link_to 'Back to goals', goals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/goals/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @goal %>

    <%= link_to 'Edit this goal', edit_goal_path(@goal), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this goal', goal_path(@goal), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to goals', goals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>